TEAM_NUM = 5
MU = 1500
SIGMA = MU / 3
INIT_SIGMA = 400
MIN_SIGMA = 250
SHUFFLE_NUM = 1000
LANE = ["TOP", "JUNGLE", "MIDDLE", "BOTTOM", "UTILITY"]
LinkDataJSON = 'data/linkdata.json'
SummonerDataCSV = 'data/summoner_data.csv'
TierData = 'data/tier.json'
EMOJI_CHECK = "✅"
REGION = 'jp1'
ACCOUNTREGION = 'ASIA'